/*global systemDictionary:true */
'use strict';

systemDictionary = {
	"HEOS Account": {
		"en": "HEOS Account",
		"de": "HEOS-Konto",
		"ru": "Аккаунт HEOS",
		"pt": "HEOS Account",
		"nl": "HEOS-account",
		"fr": "Compte HEOS",
		"it": "Account HEOS",
		"es": "Cuenta HEOS",
		"pl": "Konto HEOS",
		"zh-cn": "HEOS帐户"
	},
	"Username": {
		"en": "Username",
		"de": "Nutzername",
		"ru": "Имя пользователя",
		"pt": "Nome do usuário",
		"nl": "Gebruikersnaam",
		"fr": "Nom d'utilisateur",
		"it": "Nome utente",
		"es": "Nombre de usuario",
		"pl": "Nazwa Użytkownika",
		"zh-cn": "用户名"
	},
	"Password": {
		"en": "Password",
		"de": "Passwort",
		"ru": "пароль",
		"pt": "Senha",
		"nl": "Wachtwoord",
		"fr": "Mot de passe",
		"it": "Parola d'ordine",
		"es": "Contraseña",
		"pl": "Hasło",
		"zh-cn": "密码"
	},
	"Comfort settings": {
		"en": "Comfort settings",
		"de": "Komforteinstellungen",
		"ru": "Настройки комфорта",
		"pt": "Configurações de conforto",
		"nl": "Comfort instellingen",
		"fr": "Paramètres de confort",
		"it": "Impostazioni comfort",
		"es": "Ajustes de confort",
		"pl": "Ustawienia komfortu",
		"zh-cn": "舒适度设定"
	},
	"Automatic play on startup and unmute": {
		"en": "Automatic play on startup and unmute",
		"de": "Automatische Wiedergabe beim Starten und Aufheben der Stummschaltung",
		"ru": "Автоматическое воспроизведение при запуске и включении звука",
		"pt": "Reprodução automática ao iniciar e ativar o som",
		"nl": "Automatisch afspelen bij opstarten en dempen opheffen",
		"fr": "Lecture automatique au démarrage et réactivation du son",
		"it": "Riproduzione automatica all'avvio e riattivazione dell'audio",
		"es": "Reproducción automática al iniciar y activar el sonido",
		"pl": "Automatyczne odtwarzanie przy uruchamianiu i wyłączanie wyciszenia",
		"zh-cn": "启动和取消静音时自动播放"
	},
	"Default automatic playback command": {
		"en": "Default automatic playback command",
		"de": "Standardbefehl für die automatische Wiedergabe",
		"ru": "Команда автоматического воспроизведения по умолчанию",
		"pt": "Comando de reprodução automática padrão",
		"nl": "Standaard automatisch afspeelcommando",
		"fr": "Commande de lecture automatique par défaut",
		"it": "Comando di riproduzione automatica predefinito",
		"es": "Comando de reproducción automática predeterminado",
		"pl": "Domyślne polecenie automatycznego odtwarzania",
		"zh-cn": "默认自动播放命令"
	},
	"Automatic playback on startup and unmute": {
		"en": "Automatic playback on startup and unmute",
		"de": "Automatische Wiedergabe beim Start und Aufheben der Stummschaltung",
		"ru": "Автоматическое воспроизведение при запуске и включении звука",
		"pt": "Reprodução automática ao iniciar e ativar o som",
		"nl": "Automatisch afspelen bij opstarten en dempen opheffen",
		"fr": "Lecture automatique au démarrage et réactivation du son",
		"it": "Riproduzione automatica all'avvio e riattivazione dell'audio",
		"es": "Reproducción automática al iniciar y activar el sonido",
		"pl": "Automatyczne odtwarzanie po uruchomieniu i wyłącz wyciszenie",
		"zh-cn": "启动和取消静音时自动播放"
	},
	"Volume step": {
		"en": "Volume step",
		"de": "Lautstärkeschritt",
		"ru": "Шаг объема",
		"pt": "Passo de volume",
		"nl": "Volume stap",
		"fr": "Étape de volume",
		"it": "Passo del volume",
		"es": "Paso de volumen",
		"pl": "Krok głośności",
		"zh-cn": "音量步进"
	},
	"Mute Spotify ads": {
		"en": "Mute Spotify ads",
		"de": "Spotify-Anzeigen stumm schalten",
		"ru": "Отключить рекламу Spotify",
		"pt": "Silenciar anúncios Spotify",
		"nl": "Demp Spotify-advertenties",
		"fr": "Ignorer les annonces Spotify",
		"it": "Disattiva gli annunci Spotify",
		"es": "Silenciar anuncios de Spotify",
		"pl": "Wycisz reklamy Spotify",
		"zh-cn": "使Spotify广告静音"
	},
	"Advanced settings": {
		"en": "Advanced settings",
		"de": "Erweiterte Einstellungen",
		"ru": "Расширенные настройки",
		"pt": "Configurações avançadas",
		"nl": "Geavanceerde instellingen",
		"fr": "Réglages avancés",
		"it": "Impostazioni avanzate",
		"es": "Ajustes avanzados",
		"pl": "Zaawansowane ustawienia",
		"zh-cn": "高级设置"
	},
	"Heartbeat interval": {
		"en": "Heartbeat interval",
		"de": "Herzschlagintervall",
		"ru": "Интервал сердцебиения",
		"pt": "Intervalo de batimento cardíaco",
		"nl": "Hartslag-interval",
		"fr": "Intervalle de pulsation",
		"it": "Intervallo di battito cardiaco",
		"es": "Intervalo de latidos",
		"pl": "Interwał pulsu",
		"zh-cn": "心跳间隔"
	},
	"Heartbeat retries": {
		"en": "Heartbeat retries",
		"de": "Herzschlag Wiederholungsversuche",
		"ru": "Повторные попытки сердцебиения",
		"pt": "Tentativas de pulsação",
		"nl": "Heartbeat probeert opnieuw",
		"fr": "Tentatives de pulsation",
		"it": "Riprova a battere il cuore",
		"es": "Reintentos de latido",
		"pl": "Ponowne próby bicia serca",
		"zh-cn": "心跳重试"
	},
	"Reconnect timeout": {
		"en": "Reconnect timeout",
		"de": "Wiederverbindungs Timeout",
		"ru": "Таймаут повторного подключения",
		"pt": "Tempo limite de reconexão",
		"nl": "Time-out voor opnieuw verbinden",
		"fr": "Délai de reconnexion",
		"it": "Ricollegare il timeout",
		"es": "Tiempo de espera de reconexión",
		"pl": "Limit czasu ponownego połączenia",
		"zh-cn": "重新连接超时"
	},
	"Search interval": {
		"en": "Search interval",
		"de": "Suchintervall",
		"ru": "Интервал поиска",
		"pt": "Intervalo de pesquisa",
		"nl": "Zoekinterval",
		"fr": "Intervalle de recherche",
		"it": "Intervallo di ricerca",
		"es": "Intervalo de búsqueda",
		"pl": "Interwał wyszukiwania",
		"zh-cn": "搜索间隔"
	},
	"Play settings": {
		"en": "Play settings",
		"de": "Abspieleinstellungen",
		"ru": "Настройки игры",
		"pt": "Configurações de jogo",
		"nl": "Speel instellingen",
		"fr": "Paramètres de lecture",
		"it": "Impostazioni di riproduzione",
		"es": "Configuración de juego",
		"pl": "Odtwórz ustawienia",
		"zh-cn": "播放设定"
	},
	"Play now": {
		"en": "Play now",
		"de": "Jetzt abspielen",
		"ru": "Играть сейчас",
		"pt": "Jogue agora",
		"nl": "Nu afspelen",
		"fr": "Joue maintenant",
		"it": "Riproduci ora",
		"es": "Reproducir ahora",
		"pl": "Zagraj teraz",
		"zh-cn": "现在播放"
	},
	"Play next": {
		"en": "Play next",
		"de": "Als nächstes abspielen",
		"ru": "Играть дальше",
		"pt": "Jogar a seguir",
		"nl": "Speel daarna",
		"fr": "Jouez ensuite",
		"it": "Gioca dopo",
		"es": "Jugar siguiente",
		"pl": "Graj dalej",
		"zh-cn": "接下来播放"
	},
	"Add to end": {
		"en": "Add to end",
		"de": "Zum Ende hinzufügen",
		"ru": "Добавить в конец",
		"pt": "Adicionar ao final",
		"nl": "Toevoegen aan einde",
		"fr": "Ajouter à la fin",
		"it": "Aggiungi alla fine",
		"es": "Agregar al final",
		"pl": "Dodaj do końca",
		"zh-cn": "添加到结尾"
	},
	"Replace and play": {
		"en": "Replace and play",
		"de": "Ersetzen und spielen",
		"ru": "Замени и играй",
		"pt": "Substitua e jogue",
		"nl": "Vervangen en spelen",
		"fr": "Remplacer et jouer",
		"it": "Sostituisci e gioca",
		"es": "Reemplazar y jugar",
		"pl": "Wymień i graj",
		"zh-cn": "替换并播放"
	},
	"Queue settings": {
		"en": "Queue settings",
		"de": "Warteschlangeneinstellungen",
		"ru": "Настройки очереди",
		"pt": "Configurações de fila",
		"nl": "Wachtrij-instellingen",
		"fr": "Paramètres de file d'attente",
		"it": "Impostazioni della coda",
		"es": "Configuración de la cola",
		"pl": "Ustawienia kolejki",
		"zh-cn": "队列设置"
	},
	"All player": {
		"en": "All player",
		"de": "Alle Player",
		"ru": "Все игроки",
		"pt": "Todos os jogadores",
		"nl": "Alle spelers",
		"fr": "Tous les joueurs",
		"it": "Tutti i giocatori",
		"es": "Todo jugador",
		"pl": "Wszyscy gracze",
		"zh-cn": "所有玩家"
	},
	"All leading and non-group player": {
		"en": "All leading and non-group player",
		"de": "Alle führenden und Nicht-Gruppen Player",
		"ru": "Все ведущие и негрупповые игроки",
		"pt": "Todos jogadores líderes e não pertencentes ao grupo",
		"nl": "Alle leidende en niet-groepsspelers",
		"fr": "Tous les acteurs principaux et hors groupe",
		"it": "Tutti i protagonisti e non di gruppo",
		"es": "Todo jugador líder y no grupal",
		"pl": "Wszyscy wiodący i spoza grupy",
		"zh-cn": "所有领先和非团体玩家"
	},
	"Player IDs in state command_scope_pid": {
		"en": "Player IDs in state command_scope_pid",
		"de": "Player-IDs im State command_scope_pid",
		"ru": "Идентификаторы игроков в состоянии command_scope_pid",
		"pt": "IDs de jogador no estado command_scope_pid",
		"nl": "Speler-ID's in de status command_scope_pid",
		"fr": "ID de joueur dans l'état command_scope_pid",
		"it": "ID giocatore nello stato command_scope_pid",
		"es": "ID de jugador en el estado command_scope_pid",
		"pl": "Identyfikatory graczy w stanie command_scope_pid",
		"zh-cn": "状态为command_scope_pid的玩家ID"
	},
	"Command scope for state scope/[cmd]": {
		"en": "Command scope for state/[cmd]",
		"de": "Befehlsbereich für state/[cmd]",
		"ru": "Область действия команды для области state/[cmd]",
		"pt": "Escopo de comando para escopo de state/[cmd]",
		"nl": "Opdrachtbereik voor statusbereik state/[cmd]",
		"fr": "Portée de la commande pour la portée de state/[cmd]",
		"it": "Ambito del comando per ambito di state/[cmd]",
		"es": "Alcance del comando para el alcance del state/[cmd]",
		"pl": "Zakres poleceń dla zakresu state/[cmd]",
		"zh-cn": "状态范围/ [cmd]的命令范围"
	}
};